export const diamondProducts = [
  {
    id: "1",
    name: "1.2ct Round Brilliant Diamond",
    diamondType: "natural",
    shape: "round",
    cut: "excellent",
    color: "G",
    clarity: "VVS1",
    carat: 1.2,
    price: 8500,
    originalPrice: 9500,
    discount: 10,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    video: "https://videos.diamondfoundry.com/643655.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
  },
  {
    id: "2",
    name: "0.8ct Princess Cut Diamond",
    shape: "princess",
    cut: "ideal",
    diamondType: "lab-grown",
    color: "H",
    clarity: "VS1",
    carat: 0.8,
    price: 4200,
    originalPrice: 4800,
    discount: 12,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    video: "https://videos.diamondfoundry.com/643655.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "3",
    name: "1.5ct Cushion Cut Diamond",
    shape: "cushion",
    diamondType: "natural",
    cut: "excellent",
    color: "F",
    clarity: "VVS2",
    carat: 1.5,
    price: 12800,
    originalPrice: 14000,
    discount: 8,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    video: "https://videos.diamondfoundry.com/639039.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "4",
    name: "0.9ct Oval Diamond",
    shape: "oval",
    diamondType: "lab-grown",
    cut: "very-good",
    color: "I",
    clarity: "VS2",
    carat: 0.9,
    price: 3800,
    originalPrice: 4200,
    discount: 9,
    certification: "GIA",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "Medium",
    video: "https://videos.diamondfoundry.com/639039.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "5",
    name: "2.1ct Emerald Cut Diamond",
    shape: "emerald",
    diamondType: "natural",
    cut: "excellent",
    color: "E",
    clarity: "FL",
    carat: 2.1,
    price: 28500,
    originalPrice: 32000,
    discount: 11,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    video: "https://videos.diamondfoundry.com/610869.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "6",
    name: "0.7ct Pear Shape Diamond",
    shape: "pear",
    diamondType: "lab-grown",
    cut: "good",
    color: "J",
    clarity: "SI1",
    carat: 0.7,
    price: 2400,
    originalPrice: 2800,
    discount: 14,
    certification: "IGI",
    polish: "Good",
    symmetry: "Good",
    fluorescence: "Strong",
    video: "https://videos.diamondfoundry.com/601559.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "7",
    name: "1.1ct Marquise Diamond",
    shape: "marquise",
    diamondType: "natural",
    cut: "excellent",
    color: "F",
    clarity: "VVS1",
    carat: 1.1,
    price: 9200,
    originalPrice: 10500,
    discount: 12,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    video: "https://videos.diamondfoundry.com/638469.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "8",
    name: "1.3ct Asscher Cut Diamond",
    shape: "asscher",
    diamondType: "lab-grown",
    cut: "ideal",
    color: "G",
    clarity: "VS1",
    carat: 1.3,
    price: 6800,
    originalPrice: 7600,
    discount: 10,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    video: "https://videos.diamondfoundry.com/635188.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "9",
    name: "0.9ct Trillion Cut Diamond",
    shape: "trillion",
    diamondType: "natural",
    cut: "very-good",
    color: "H",
    clarity: "VS2",
    carat: 0.9,
    price: 4500,
    originalPrice: 5200,
    discount: 13,
    certification: "GIA",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "Medium",
    video: "https://videos.diamondfoundry.com/639074.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "10",
    name: "1.8ct Cushion Cut Diamond",
    shape: "cushion",
    diamondType: "lab-grown",
    cut: "excellent",
    color: "E",
    clarity: "VVS2",
    carat: 1.8,
    price: 11200,
    originalPrice: 12800,
    discount: 12,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    video: "https://videos.diamondfoundry.com/639682.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "11",
    name: "1.0ct Princess Cut Diamond",
    shape: "princess",
    diamondType: "natural",
    cut: "ideal",
    color: "F",
    clarity: "VVS1",
    carat: 1.0,
    price: 7200,
    originalPrice: 8000,
    discount: 10,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    video: "https://videos.diamondfoundry.com/638670.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "12",
    name: "1.4ct Princess Cut Diamond",
    shape: "princess",
    diamondType: "lab-grown",
    cut: "excellent",
    color: "G",
    clarity: "VS1",
    carat: 1.4,
    price: 5800,
    originalPrice: 6500,
    discount: 11,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    video: "https://videos.diamondfoundry.com/639060.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "13",
    name: "0.8ct Pear Shape Diamond",
    shape: "pear",
    diamondType: "natural",
    cut: "very-good",
    color: "I",
    clarity: "SI1",
    carat: 0.8,
    price: 3200,
    originalPrice: 3600,
    discount: 11,
    certification: "IGI",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "Strong",
    video: "https://videos.diamondfoundry.com/634629.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "14",
    name: "1.6ct Asscher Cut Diamond",
    shape: "asscher",
    diamondType: "natural",
    cut: "excellent",
    color: "E",
    clarity: "VVS2",
    carat: 1.6,
    price: 15800,
    originalPrice: 17500,
    discount: 10,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    video: "https://videos.diamondfoundry.com/636036.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
  {
    id: "15",
    name: "2.2ct Round Brilliant Diamond",
    shape: "round",
    diamondType: "natural",
    cut: "ideal",
    color: "D",
    clarity: "FL",
    carat: 2.2,
    price: 35000,
    originalPrice: 38500,
    discount: 9,
    certification: "GIA",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    video: "https://videos.diamondfoundry.com/636036.mp4",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
  },
]
